### PR TITLE
bug: optimize Timestamp conversions to/from string

### LINKED ISSUE #1088: Optimize TimestampFromString()
`TimestampFromString()` appears to be the slowest of our "string -> data-type" conversion functions.  Beneath the hood it uses `std::get_time()`, which is overly general for our purpose, and could be avoided.

Aside: At the same time, we should probably avoid `std::put_time()` in `TimestampToString()`.

### PR DESCRIPTION
**Pull request by devbww**
Introduce versions of `internal::FormatTime()` and `internal::ParseTime()`
that do not take a format-specifier string. Instead they only format and
parse _"%Y-%m-%dT%H:%M:%S"_, allowing them to be very specific and fast.  In
particular this allows us to avoid `std::put_time()` and `std::get_time()`
(and we avoid `std::sscanf()` too). Use these to implemented the Spanner
`TimestampToString()` and `TimestampFromString()` conversion functions.
Fixes #1088.

Note: The new, format-specifier-less `internal::FormatTime()` produces a
4-character year when possible (unlike the _"%Y"_ format specifier).

Also introduce formatting and parsing of _"[-+]HH:MM"_ UTC offset fields.
While we will always produce a _"Z"_ offset in `TimestampToString()` for
Spanner, this will enable some refactoring of the time-formatting code
between all the Cloud C++ projects. See #145.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1110)

### CODE REVIEW

**Comment by devbww** [comment]
For the record, here is what I got from my first attempt to run the "read-timestamp" benchmark.

Before:
```
  UsingStub     experiment CpuTimePerRow
1     false read-timestamp           Inf
2      true read-timestamp      4.087792
```
After:
```
  UsingStub     experiment CpuTimePerRow
1     false read-timestamp     75.211959
2      true read-timestamp      4.110392
```
An infinite improvement.  :-)

File: google/cloud/spanner/internal/time.cc [hunk 1]
```diff
@@ -185,43 +192,92 @@ std::string TimestampToString(Timestamp ts) {
...
+      case 'Z':  // Zulu time
+      case 'z': {
+        ++pos;
+        break;
+      }
+      case '+':  // [-+]HH:MM
+      case '-': {
+        // Parse colon-separated hours, minutes, but not (yet) seconds.
+        std::array<std::chrono::minutes::rep, 2> fields = {{0, 0}};
+        auto it = fields.begin();
```
Comment (devbww) [inline google/cloud/spanner/internal/time.cc]: > Should we refactor ParseInt() from time_format.cc and use it here?

I would say not.  The implementations are sufficiently simple and sufficiently distinct that trying to factor out commonality would, I think, be more trouble than it is worth.

File: google/cloud/spanner/internal/time_format.cc [hunk 2]
```diff
@@ -34,6 +37,62 @@ namespace spanner {
...
+char const* ParseInt(char const* dp, int min, int max, int* vp) {
+  int value = 0;
+  bool neg = false;
+  if (*dp == '-') {
+    neg = true;
+    ++dp;
+  }
+  char const* const bp = dp;
+  constexpr int kMin = std::numeric_limits<int>::min();
+  while (char const* cp = std::strchr(kDigits, *dp)) {
```
Comment (devbww) [inline google/cloud/spanner/internal/time_format.cc]: > I am guessing this explicit look is here because std::from_chars() is unavailable to us, and std::strtol() is too slow? Consider a comment explaining why.

Added such a comment.

File: google/cloud/spanner/internal/time_format.cc [hunk 3]
```diff
@@ -34,6 +37,62 @@ namespace spanner {
...
+
+// Note: tm.tm_year and tm.tm_mon are unadjusted (i.e., have true values).
+bool ValidDay(std::tm const& tm) {
+  static constexpr std::array<int, 1 + 12> kMonthDays = {
+      {-1, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}  // non leap year
+  };
+  if (tm.tm_mon == 2 && LeapYear(tm.tm_year)) {
+    return tm.tm_mday <= 29;
+  }
+  return tm.tm_mday <= kMonthDays[tm.tm_mon];
```
Comment (devbww) [inline google/cloud/spanner/internal/time_format.cc]: > Should we worry about out of range values for tm.tm_mon?

No ... we only pass a `tm` whose `tm_mon` and `tm_day` fields have already been range-checked to [1:12] and [1:31] respectively.

File: google/cloud/spanner/internal/time_format.cc [hunk 4]
```diff
@@ -70,6 +169,38 @@ std::size_t ParseTime(char const* fmt, std::string const& s, std::tm* tm) {
 #endif
 }
 
+std::size_t ParseTime(std::string const& s, std::tm* tm) {
+  constexpr auto kYearMin = std::numeric_limits<int>::min() + 1900;
+  constexpr auto kYearMax = std::numeric_limits<int>::max();
+  std::tm tmp{};
+  char const* dp = ParseInt(s.c_str(), kYearMin, kYearMax, &tmp.tm_year);
+  if (dp != nullptr && *dp == '-') {
```
Comment (devbww) [inline google/cloud/spanner/internal/time_format.cc]: > nit: I prefer to return early instead of indenting

Yeah ... a possibility.  But in this particular case I believe I find indenting more readable.  Certainly having only one "success" and one "error" `return` helps a little.

File: google/cloud/spanner/internal/time_format_test.cc [hunk 5]
```diff
@@ -27,13 +27,86 @@ constexpr auto kTimeFormat = "%Y-%m-%dT%H:%M:%S";
...
+#endif
+
+  tm.tm_year = 123 - 1900;
+  tm.tm_mon = 6 - 1;
+  tm.tm_mday = 21;
+  tm.tm_hour = 16;
+  tm.tm_min = 52;
+  tm.tm_sec = 22;
+#if defined(__APPLE__) || defined(_WIN32)
+  EXPECT_EQ("0123-06-21T16:52:22", FormatTime(kTimeFormat, tm));
```
Comment (devbww) [inline google/cloud/spanner/internal/time_format_test.cc]: > Do we know if Cloud Spanner accepts both formats?

I'll say it doesn't matter because, in the case of Spanner, we don't use the general form of `FormatTime()` (i.e., the one with a `fmt` string), so we're are not subject to the `"%Y"` vagaries.

**Comment by devbww** [comment]
> When we take a dep on Abseil, which I think will be soon, I think we can delete ~all of this and offload the work to Abseil Time. Does that sound right?

Yes, I believe that would be possible, although there may be some specifics we're overlooking at the moment.  Certainly the parsing code looks much the same.
