### PR TITLE
bug: Make internal::ConnectionImpl thread-safe.

### LINKED ISSUE #423: ConnectionImpl is not thread safe.
The `sessions_` variable needs some kind of locking around it.

### PR DESCRIPTION
**Pull request by coryan**
Fixes #423.

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/406)

### CODE REVIEW

**Comment by coryan** [comment]
For what is worth: both the tsan build and helgrind detect problems when I remove the code using the `mu_` mutex. Both pass with the current code.

File: google/cloud/spanner/internal/connection_impl.cc [hunk 1]
```diff
@@ -72,6 +78,14 @@ StatusOr<ConnectionImpl::SessionHolder> ConnectionImpl::GetSession() {
   return SessionHolder(std::move(*response->mutable_name()), this);
 }
 
+void ConnectionImpl::ReleaseSession(std::string session) {
+  if (session.empty()) {
```
Comment (devbww) [inline google/cloud/spanner/internal/connection_impl.cc]: Why should we make this check?

File: google/cloud/spanner/internal/connection_impl.h [hunk 2]
```diff
@@ -54,7 +55,10 @@ class ConnectionImpl : public Connection {
    public:
     SessionHolder(std::string session, ConnectionImpl* conn) noexcept
         : session_(std::move(session)), conn_(conn) {}
-    ~SessionHolder() { conn_->sessions_.emplace_back(std::move(session_)); }
+    ~SessionHolder() {
+      conn_->ReleaseSession(std::move(session_));
+      session_.clear();
```
[the remark this answers is not in the document]
Comment (coryan) [reply google/cloud/spanner/internal/connection_impl.h]: Done.

**Comment by devbww** [comment]
> What we want is to return the session exactly once. I think (but check my math) that to achieve this we need to disallow copy on SessionHolder, and make the move copy and assignment clear something to make sure the destructor only takes action once.

Do we even need move copy and assignment?  Can we just make `session_` and `conn_` const to stop anything bad from happening to a `SessionHolder`?

File: google/cloud/spanner/internal/connection_impl_test.cc [hunk 3]
```diff
@@ -497,6 +500,69 @@ TEST(ConnectionImplTest, RollbackSuccess) {
...
+  int const per_thread_iterations = 1000;
+  auto const thread_count = []() -> unsigned {
+    if (std::thread::hardware_concurrency() == 0) {
+      return 16;
+    }
+    return std::thread::hardware_concurrency();
+  }();
+
+  auto runner = [](int thread_id, int iterations,
+                   std::shared_ptr<Connection> const& conn) {
```
[the remark this answers is not in the document]
Comment (coryan) [reply google/cloud/spanner/internal/connection_impl_test.cc]: Sure, but it has to be `T&` because we are calling non-const member functions.  Note that this requires a `std::ref` below because `std::async` copies every argument.

**Comment by coryan** [comment]
> > What we want is to return the session exactly once. I think (but check my math) that to achieve this we need to disallow copy on SessionHolder, and make the move copy and assignment clear something to make sure the destructor only takes action once.
> 
> Do we even need move copy and assignment? Can we just make `session_` and `conn_` const to stop anything bad from happening to a `SessionHolder`?

I think we need at least a move constructor because we put `SessionHolder` in a `StatusOr<SessionHolder>`.

**Comment by coryan** [comment]
@devbww PTAL.

**Comment by coryan** [comment]
Rebased to resolve conflicts.

**Comment by devbww** [comment]
Have you looked at the TSan failure (I haven't :-).

**Comment by coryan** [comment]
I noticed a few minutes before you asked, so far nothing obvious, and I needed to change the TSAN build to include line numbers.

**Comment by coryan** [comment]
Good news, it was a bug in the test. Fixed now, ran 1000 iterations of the test without error.  Rebased for good measure and will update the `.bazelrc` file in a separate PR.

File: google/cloud/spanner/internal/connection_impl_test.cc [hunk 4]
```diff
@@ -579,7 +579,7 @@ TEST(ConnectionImplTest, MultipleThreads) {
   auto db = Database("project", "instance", "database");
   std::string const session_prefix = "test-session-prefix-";
   std::string const transaction_id = "test-txn-id";
-  int session_counter = 0;
+  std::atomic<int> session_counter(0);
```
Comment (devbww) [inline google/cloud/spanner/internal/connection_impl_test.cc]: `#include <atomic>`

Comment (coryan) [reply google/cloud/spanner/internal/connection_impl_test.cc]: Done.
