### PR TITLE
fix: associate each `Session` with a `Channel`

### LINKED ISSUE #1344: SessionPool per-channel accounting is incorrect for dissociated or bad Sessions.
SessionPool maintains a per-Channel session-count; however, if a Session is dissociated from the pool or marked bad, the count is not properly updated.

### PR DESCRIPTION
**Pull request by mr-salty**
Factor the `SessionPool::ChannelInfo` struct out to a stand-alone
object, so we can store a `shared_ptr` to it in each `Session`.

This allows us to properly account for `Sessions` that are marked bad or
disassociated from the pool.  Previously, the per-Channel session count
was not being decremented in those cases.

Since the `Channel` also holds a `shared_ptr<Stub>`, we can eliminate
the `Session::stub_` member.

Fixes #1344

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1346)

### CODE REVIEW

**Comment by mr-salty** [comment]
___
*[google/cloud/spanner/internal/channel.h, line 34 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1346#-M2-nP3p9a_D6QfeZIEd:-M2-nP3p9a_D6QfeZIEe:bx15ucd) ([raw file](https://github.com/googleapis/google-cloud-cpp-spanner/blob/58d0278ab4dbbf2f7c9ccc5bea671bb44c504cc6/google/cloud/spanner/internal/channel.h#L34)):*
> ```objc
>   explicit Channel(std::shared_ptr<SpannerStub> stub_param)
>       : stub(std::move(stub_param)) {}
> ```

FWIW, I was debating disabling copy/move here because it's easy to make an inadvertent copy, and that causes some subtle bugs.  Internally we tend to make things no copy/no move by default but don't really seem to do it in this project.

File: google/cloud/spanner/internal/channel.h [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+#ifndef GOOGLE_CLOUD_CPP_SPANNER_GOOGLE_CLOUD_SPANNER_INTERNAL_CHANNEL_H
+#define GOOGLE_CLOUD_CPP_SPANNER_GOOGLE_CLOUD_SPANNER_INTERNAL_CHANNEL_H
+
+#include "google/cloud/spanner/internal/spanner_stub.h"
+#include <memory>
+
+namespace google {
+namespace cloud {
+namespace spanner {
+inline namespace SPANNER_CLIENT_NS {
```
Comment (devbww) [inline google/cloud/spanner/internal/channel.h]: `#include "google/cloud/spanner/version.h"`

File: google/cloud/spanner/internal/channel.h [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+namespace internal {
+
+/**
+ * `Channel` represents a single gRPC Channel/Stub.
+ */
+struct Channel {
+  /// @p stub must not be nullptr
```
Comment (devbww) [inline google/cloud/spanner/internal/channel.h]: s/stub/stub_param/

File: google/cloud/spanner/internal/session.h [hunk 3]
```diff
@@ -15,6 +15,7 @@
 #ifndef GOOGLE_CLOUD_CPP_SPANNER_GOOGLE_CLOUD_SPANNER_INTERNAL_SESSION_H
 #define GOOGLE_CLOUD_CPP_SPANNER_GOOGLE_CLOUD_SPANNER_INTERNAL_SESSION_H
 
+#include "google/cloud/spanner/internal/channel.h"
 #include "google/cloud/spanner/internal/spanner_stub.h"
```
Comment (devbww) [inline google/cloud/spanner/internal/session.h]: No longer needed?

File: google/cloud/spanner/internal/channel.h [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+ * `Channel` represents a single gRPC Channel/Stub.
+ */
+struct Channel {
+  /// @p stub_param must not be nullptr
+  explicit Channel(std::shared_ptr<SpannerStub> stub_param)
+      : stub(std::move(stub_param)) {}
+
+  // This class is not copyable or movable.
+  Channel(const Channel&) = delete;
+  Channel& operator=(const Channel&) = delete;
```
Comment (devbww) [inline google/cloud/spanner/internal/channel.h]: East const.

File: google/cloud/spanner/internal/channel.h [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+
+/**
+ * `Channel` represents a single gRPC Channel/Stub.
+ */
+struct Channel {
+  /// @p stub_param must not be nullptr
+  explicit Channel(std::shared_ptr<SpannerStub> stub_param)
+      : stub(std::move(stub_param)) {}
+
+  // This class is not copyable or movable.
```
Comment (devbww) [inline google/cloud/spanner/internal/channel.h]:
```
  Channel(Channel&&) = delete;
  Channel& operator=(Channel&&) = delete;
```
as well?

**Comment by mr-salty** [comment]
___
*[google/cloud/spanner/internal/channel.h, line 36 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1346#-M2-nKU42WOHcfuai8To-r3-36:-M20G47I4Ov3u4CTE4yY:b-19vmfz) ([raw file](https://github.com/googleapis/google-cloud-cpp-spanner/blob/a6a2cf13e93c74a79306524969d159fb9d1ee7ea/google/cloud/spanner/internal/channel.h#L36)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Not necessary, but I believe we still choose to do it.
</blockquote></details>

I see no documentation to support your assertion.

https://github.com/googleapis/google-cloud-cpp-common/blob/master/doc/cpp-style-guide.md
